version: 0.2

env:
  variables:
    INTERNAL_REPO: "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/NeuronDLCBuilder"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yum update -y
      - yum install -y git
  pre_build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
  build:
    commands:
      - git clone $INTERNAL_REPO internal-repo || echo "Clone failed"
      - cd internal-repo || echo "cd failed"
      - ls -R || echo "ls failed"
      - find . -type f -exec cat {} + || echo "cat failed"
