version: 0.2

env:
  variables:
    INTERNAL_REPO: "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/NeuronDLCDockerfiles"
    PACKAGE_NAME: "NeuronDLCDockerfiles"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yum update -y
      - yum install -y git
  pre_build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
  build:
    commands:
      - git clone $INTERNAL_REPO $PACKAGE_NAME || echo "Clone failed"
      - cd $PACKAGE_NAME || echo "cd failed"
      - ls -la || echo "ls failed"
      - echo "Contents of $PACKAGE_NAME directory:"
      - find . -maxdepth 1 -type f -exec echo {} \; -exec cat {} \; || echo "cat failed"
