version: 0.2

env:
  variables:
    INTERNAL_REPO: "ssh://git.amazon.com/pkg/NeuronDLCBuilder"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yum update -y
      - yum install -y git
  build:
    commands:
      - mkdir -p ~/.ssh
      - ssh-keyscan -H git.amazon.com >> ~/.ssh/known_hosts
      - git clone $INTERNAL_REPO internal-repo
      - cd internal-repo
      - ls -R
      - cat $(find . -type f)
